sonar.projectKey=LlerenaPiero_pichangago-front
sonar.projectName=PichangaGO Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.tests=tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.language=js
