/* ============================================================
   PichangaGO V2 - Script 02
   RECREAR ESQUEMA COMPLETO

   IMPORTANTE:
   - Ejecuta este script conectado directamente a la base PichangaGO.
   - No ejecutes este script conectado a master.
   - Este script BORRA las tablas existentes y las crea nuevamente.
   - Compatible con Azure SQL Database porque NO usa USE.
   ============================================================ */

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    /* ============================================================
       1. LIMPIEZA DE TABLAS EXISTENTES
       Se eliminan en orden inverso a las dependencias por FK.
       ============================================================ */

    DROP TABLE IF EXISTS [dbo].[COMPROBANTES];
    DROP TABLE IF EXISTS [dbo].[REEMBOLSOS];
    DROP TABLE IF EXISTS [dbo].[PAGOS];
    DROP TABLE IF EXISTS [dbo].[REVIEWS];
    DROP TABLE IF EXISTS [dbo].[OFERTAS];
    DROP TABLE IF EXISTS [dbo].[RESERVAS];
    DROP TABLE IF EXISTS [dbo].[SLOTS];
    DROP TABLE IF EXISTS [dbo].[HORARIOS];
    DROP TABLE IF EXISTS [dbo].[FOTOS_CANCHA];
    DROP TABLE IF EXISTS [dbo].[CANCHAS];
    DROP TABLE IF EXISTS [dbo].[LOCALES];
    DROP TABLE IF EXISTS [dbo].[TIPOS_CANCHA];
    DROP TABLE IF EXISTS [dbo].[LIQUIDACIONES];
    DROP TABLE IF EXISTS [dbo].[SUSCRIPCIONES];
    DROP TABLE IF EXISTS [dbo].[TOKENS_RECUPERACION];
    DROP TABLE IF EXISTS [dbo].[DUENOS];
    DROP TABLE IF EXISTS [dbo].[USUARIOS];

    /* ============================================================
       2. TABLAS PRINCIPALES
       ============================================================ */

    CREATE TABLE [dbo].[USUARIOS](
        [ID_USER]        CHAR(10)       NOT NULL,
        [EMAIL]          VARCHAR(100)   NOT NULL,
        [PSW_HSH]        VARCHAR(255)   NOT NULL,
        [NOMBRE]         VARCHAR(50)    NOT NULL,
        [APELLIDO]       VARCHAR(50)    NOT NULL,
        [TELEFONO]       VARCHAR(15)    NULL,
        [ROL]            VARCHAR(20)    NOT NULL,
        [ESTADO]         VARCHAR(20)    NOT NULL CONSTRAINT [DF_USUARIOS_ESTADO] DEFAULT ('ACTIVO'),
        [FECHA_CREA]     DATETIME2(0)   NOT NULL CONSTRAINT [DF_USUARIOS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        [TOKEN_VERSION]  INT            NOT NULL CONSTRAINT [DF_USUARIOS_TOKEN_VERSION] DEFAULT (1),
        CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED ([ID_USER]),
        CONSTRAINT [UQ_USUARIOS_EMAIL] UNIQUE ([EMAIL]),
        CONSTRAINT [CK_USUARIOS_ROL] CHECK ([ROL] IN ('CLIENTE','DUENO','ADMIN')),
        CONSTRAINT [CK_USUARIOS_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','INACTIVO','BLOQUEADO'))
    );

    CREATE TABLE [dbo].[DUENOS](
        [ID_DUENO]          CHAR(10)       NOT NULL,
        [ID_USER]           CHAR(10)       NOT NULL,
        [RUC]               VARCHAR(11)    NULL,
        [RAZON_SOCIAL]      VARCHAR(100)   NULL,
        [CCI]               VARCHAR(50)    NOT NULL,
        [BANCO]             VARCHAR(50)    NULL,
        [ESTADO]            VARCHAR(20)    NOT NULL CONSTRAINT [DF_DUENOS_ESTADO] DEFAULT ('ACTIVO'),
        [FECHA_AFILIACION]  DATETIME2(0)   NOT NULL CONSTRAINT [DF_DUENOS_FECHA_AFILIACION] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_DUENOS] PRIMARY KEY CLUSTERED ([ID_DUENO]),
        CONSTRAINT [FK_DUENOS_USUARIOS] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USUARIOS]([ID_USER]),
        CONSTRAINT [UQ_DUENOS_ID_USER] UNIQUE ([ID_USER]),
        CONSTRAINT [CK_DUENOS_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','INACTIVO','SUSPENDIDO')),
        CONSTRAINT [CK_DUENOS_RUC] CHECK ([RUC] IS NULL OR (LEN([RUC]) = 11 AND [RUC] NOT LIKE '%[^0-9]%'))
    );

    CREATE UNIQUE NONCLUSTERED INDEX [UX_DUENOS_RUC]
    ON [dbo].[DUENOS]([RUC])
    WHERE [RUC] IS NOT NULL;

    CREATE TABLE [dbo].[LOCALES](
        [ID_LOCAL]      CHAR(10)       NOT NULL,
        [ID_DUENO]      CHAR(10)       NOT NULL,
        [NOMBRE]        VARCHAR(100)   NOT NULL,
        [DIRECCION]     VARCHAR(150)   NOT NULL,
        [REFERENCIA]    VARCHAR(200)   NULL,
        [PAIS]          VARCHAR(50)    NOT NULL CONSTRAINT [DF_LOCALES_PAIS] DEFAULT ('PERU'),
        [DEPARTAMENTO]  VARCHAR(50)    NOT NULL,
        [PROVINCIA]     VARCHAR(50)    NOT NULL,
        [DISTRITO]      VARCHAR(50)    NOT NULL,
        [UBIGEO]        VARCHAR(6)     NULL,
        [LATITUD]       DECIMAL(10,7)  NULL,
        [LONGITUD]      DECIMAL(10,7)  NULL,
        [ESTADO]        VARCHAR(20)    NOT NULL CONSTRAINT [DF_LOCALES_ESTADO] DEFAULT ('ACTIVO'),
        [FECHA_CREA]    DATETIME2(0)   NOT NULL CONSTRAINT [DF_LOCALES_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_LOCALES] PRIMARY KEY CLUSTERED ([ID_LOCAL]),
        CONSTRAINT [FK_LOCALES_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [CK_LOCALES_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','INACTIVO','SUSPENDIDO')),
        CONSTRAINT [CK_LOCALES_LATITUD] CHECK ([LATITUD] IS NULL OR ([LATITUD] BETWEEN -90 AND 90)),
        CONSTRAINT [CK_LOCALES_LONGITUD] CHECK ([LONGITUD] IS NULL OR ([LONGITUD] BETWEEN -180 AND 180)),
        CONSTRAINT [CK_LOCALES_UBIGEO] CHECK ([UBIGEO] IS NULL OR (LEN([UBIGEO]) = 6 AND [UBIGEO] NOT LIKE '%[^0-9]%'))
    );

    CREATE TABLE [dbo].[TIPOS_CANCHA](
        [ID_TIPO_CANCHA]       CHAR(10)       NOT NULL,
        [CODIGO]               VARCHAR(10)    NOT NULL,
        [NOMBRE]               VARCHAR(50)    NOT NULL,
        [JUGADORES_POR_EQUIPO] INT            NOT NULL,
        [JUGADORES_TOTAL]      INT            NOT NULL,
        [TAMANO]               VARCHAR(20)    NOT NULL,
        [DESCRIPCION]          VARCHAR(150)   NULL,
        [ESTADO]               VARCHAR(20)    NOT NULL CONSTRAINT [DF_TIPOS_CANCHA_ESTADO] DEFAULT ('ACTIVO'),
        CONSTRAINT [PK_TIPOS_CANCHA] PRIMARY KEY CLUSTERED ([ID_TIPO_CANCHA]),
        CONSTRAINT [UQ_TIPOS_CANCHA_CODIGO] UNIQUE ([CODIGO]),
        CONSTRAINT [CK_TIPOS_CANCHA_TAMANO] CHECK ([TAMANO] IN ('PEQUENA','MEDIANA','GRANDE')),
        CONSTRAINT [CK_TIPOS_CANCHA_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','INACTIVO')),
        CONSTRAINT [CK_TIPOS_CANCHA_JUGADORES] CHECK ([JUGADORES_POR_EQUIPO] > 0 AND [JUGADORES_TOTAL] > 0)
    );

    CREATE TABLE [dbo].[CANCHAS](
        [ID_CANCHA]           CHAR(10)       NOT NULL,
        [ID_LOCAL]            CHAR(10)       NOT NULL,
        [ID_DUENO]            CHAR(10)       NOT NULL,
        [ID_TIPO_CANCHA]      CHAR(10)       NOT NULL,
        [NOMBRE]              VARCHAR(80)    NOT NULL,
        [DESCRIPCION]         VARCHAR(250)   NULL,
        [TIPO_SUPERFICIE]     VARCHAR(30)    NOT NULL,
        [ES_TECHADA]          BIT            NOT NULL CONSTRAINT [DF_CANCHAS_ES_TECHADA] DEFAULT (0),
        [TIENE_ILUMINACION]   BIT            NOT NULL CONSTRAINT [DF_CANCHAS_TIENE_ILUMINACION] DEFAULT (1),
        [PRECIO_BASE]         DECIMAL(8,2)   NOT NULL,
        [PRECIO_HORA_PUNTA]   DECIMAL(8,2)   NOT NULL,
        [PRECIO_HORA_VALLE]   DECIMAL(8,2)   NOT NULL,
        [ESTADO]              VARCHAR(20)    NOT NULL CONSTRAINT [DF_CANCHAS_ESTADO] DEFAULT ('DISPONIBLE'),
        [FECHA_CREA]          DATETIME2(0)   NOT NULL CONSTRAINT [DF_CANCHAS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_CANCHAS] PRIMARY KEY CLUSTERED ([ID_CANCHA]),
        CONSTRAINT [FK_CANCHAS_LOCALES] FOREIGN KEY ([ID_LOCAL]) REFERENCES [dbo].[LOCALES]([ID_LOCAL]),
        CONSTRAINT [FK_CANCHAS_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [FK_CANCHAS_TIPOS_CANCHA] FOREIGN KEY ([ID_TIPO_CANCHA]) REFERENCES [dbo].[TIPOS_CANCHA]([ID_TIPO_CANCHA]),
        CONSTRAINT [CK_CANCHAS_SUPERFICIE] CHECK ([TIPO_SUPERFICIE] IN ('GRASS_SINTETICO','GRASS_NATURAL','LOSA','TIERRA','OTRO')),
        CONSTRAINT [CK_CANCHAS_ESTADO] CHECK ([ESTADO] IN ('DISPONIBLE','MANTENIMIENTO','INACTIVA')),
        CONSTRAINT [CK_CANCHAS_PRECIOS] CHECK ([PRECIO_BASE] >= 0 AND [PRECIO_HORA_PUNTA] >= 0 AND [PRECIO_HORA_VALLE] >= 0)
    );

    CREATE TABLE [dbo].[FOTOS_CANCHA](
        [ID_FOTO]       CHAR(10)       NOT NULL,
        [ID_CANCHA]     CHAR(10)       NOT NULL,
        [URL_FOTO]      VARCHAR(500)   NOT NULL,
        [ES_PRINCIPAL]  BIT            NOT NULL CONSTRAINT [DF_FOTOS_CANCHA_ES_PRINCIPAL] DEFAULT (0),
        [ORDEN]         INT            NOT NULL CONSTRAINT [DF_FOTOS_CANCHA_ORDEN] DEFAULT (1),
        [FECHA_SUBIDA]  DATETIME2(0)   NOT NULL CONSTRAINT [DF_FOTOS_CANCHA_FECHA_SUBIDA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_FOTOS_CANCHA] PRIMARY KEY CLUSTERED ([ID_FOTO]),
        CONSTRAINT [FK_FOTOS_CANCHA_CANCHAS] FOREIGN KEY ([ID_CANCHA]) REFERENCES [dbo].[CANCHAS]([ID_CANCHA]),
        CONSTRAINT [CK_FOTOS_CANCHA_ORDEN] CHECK ([ORDEN] > 0)
    );

    CREATE UNIQUE NONCLUSTERED INDEX [UX_FOTOS_CANCHA_PRINCIPAL]
    ON [dbo].[FOTOS_CANCHA]([ID_CANCHA])
    WHERE [ES_PRINCIPAL] = 1;

    CREATE TABLE [dbo].[HORARIOS](
        [ID_HORARIO]    CHAR(10)       NOT NULL,
        [ID_CANCHA]     CHAR(10)       NOT NULL,
        [ID_DUENO]      CHAR(10)       NOT NULL,
        [DIA_SEMANA]    INT            NOT NULL,
        [HORA_INICIO]   TIME(0)        NOT NULL,
        [HORA_FIN]      TIME(0)        NOT NULL,
        [TIPO_PRECIO]   VARCHAR(20)    NOT NULL,
        [ESTADO]        VARCHAR(20)    NOT NULL CONSTRAINT [DF_HORARIOS_ESTADO] DEFAULT ('ACTIVO'),
        [FECHA_CREA]    DATETIME2(0)   NOT NULL CONSTRAINT [DF_HORARIOS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_HORARIOS] PRIMARY KEY CLUSTERED ([ID_HORARIO]),
        CONSTRAINT [FK_HORARIOS_CANCHAS] FOREIGN KEY ([ID_CANCHA]) REFERENCES [dbo].[CANCHAS]([ID_CANCHA]),
        CONSTRAINT [FK_HORARIOS_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [CK_HORARIOS_DIA] CHECK ([DIA_SEMANA] BETWEEN 1 AND 7),
        CONSTRAINT [CK_HORARIOS_HORA] CHECK ([HORA_FIN] > [HORA_INICIO]),
        CONSTRAINT [CK_HORARIOS_TIPO_PRECIO] CHECK ([TIPO_PRECIO] IN ('BASE','PUNTA','VALLE')),
        CONSTRAINT [CK_HORARIOS_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','INACTIVO'))
    );

    CREATE TABLE [dbo].[SLOTS](
        [ID_SLOT]        CHAR(10)       NOT NULL,
        [ID_HORARIO]     CHAR(10)       NOT NULL,
        [ID_CANCHA]      CHAR(10)       NOT NULL,
        [ID_DUENO]       CHAR(10)       NOT NULL,
        [FECHA]          DATE           NOT NULL,
        [HORA_INICIO]    TIME(0)        NOT NULL,
        [HORA_FIN]       TIME(0)        NOT NULL,
        [PRECIO_FINAL]   DECIMAL(8,2)   NOT NULL,
        [ESTADO]         VARCHAR(20)    NOT NULL CONSTRAINT [DF_SLOTS_ESTADO] DEFAULT ('DISPONIBLE'),
        [FECHA_BLOQUEO]  DATETIME2(0)   NULL,
        [FECHA_EXPIRA]   DATETIME2(0)   NULL,
        [FECHA_CREA]     DATETIME2(0)   NOT NULL CONSTRAINT [DF_SLOTS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_SLOTS] PRIMARY KEY CLUSTERED ([ID_SLOT]),
        CONSTRAINT [FK_SLOTS_HORARIOS] FOREIGN KEY ([ID_HORARIO]) REFERENCES [dbo].[HORARIOS]([ID_HORARIO]),
        CONSTRAINT [FK_SLOTS_CANCHAS] FOREIGN KEY ([ID_CANCHA]) REFERENCES [dbo].[CANCHAS]([ID_CANCHA]),
        CONSTRAINT [FK_SLOTS_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [CK_SLOTS_HORA] CHECK ([HORA_FIN] > [HORA_INICIO]),
        CONSTRAINT [CK_SLOTS_PRECIO] CHECK ([PRECIO_FINAL] >= 0),
        CONSTRAINT [CK_SLOTS_ESTADO] CHECK ([ESTADO] IN ('DISPONIBLE','BLOQUEADO','RESERVADO','NO_DISPONIBLE','EXPIRADO'))
    );

    CREATE TABLE [dbo].[RESERVAS](
        [ID_RESERVA]         CHAR(10)       NOT NULL,
        [ID_USER]            CHAR(10)       NOT NULL,
        [ID_SLOT]            CHAR(10)       NOT NULL,
        [ID_HORARIO]         CHAR(10)       NOT NULL,
        [ID_CANCHA]          CHAR(10)       NOT NULL,
        [ID_DUENO]           CHAR(10)       NOT NULL,
        [PRECIO_BASE]        DECIMAL(8,2)   NOT NULL,
        [COMISION_QR]        DECIMAL(8,2)   NOT NULL CONSTRAINT [DF_RESERVAS_COMISION_QR] DEFAULT (0),
        [DESCUENTO]          DECIMAL(8,2)   NOT NULL CONSTRAINT [DF_RESERVAS_DESCUENTO] DEFAULT (0),
        [MONTO_TOTAL]        DECIMAL(8,2)   NOT NULL,
        [ESTADO]             VARCHAR(20)    NOT NULL CONSTRAINT [DF_RESERVAS_ESTADO] DEFAULT ('PENDIENTE'),
        [FECHA_CREA]         DATETIME2(0)   NOT NULL CONSTRAINT [DF_RESERVAS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        [FECHA_CONFIRMADA]   DATETIME2(0)   NULL,
        [FECHA_CANCELADA]    DATETIME2(0)   NULL,
        [CANCELADO_POR]      VARCHAR(20)    NULL,
        [PORCENTAJE_REEMB]   INT            NULL,
        CONSTRAINT [PK_RESERVAS] PRIMARY KEY CLUSTERED ([ID_RESERVA]),
        CONSTRAINT [FK_RESERVAS_USUARIOS] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USUARIOS]([ID_USER]),
        CONSTRAINT [FK_RESERVAS_SLOTS] FOREIGN KEY ([ID_SLOT]) REFERENCES [dbo].[SLOTS]([ID_SLOT]),
        CONSTRAINT [FK_RESERVAS_HORARIOS] FOREIGN KEY ([ID_HORARIO]) REFERENCES [dbo].[HORARIOS]([ID_HORARIO]),
        CONSTRAINT [FK_RESERVAS_CANCHAS] FOREIGN KEY ([ID_CANCHA]) REFERENCES [dbo].[CANCHAS]([ID_CANCHA]),
        CONSTRAINT [FK_RESERVAS_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [CK_RESERVAS_ESTADO] CHECK ([ESTADO] IN ('PENDIENTE','CONFIRMADA','CANCELADA','EXPIRADA','REEMBOLSADA')),
        CONSTRAINT [CK_RESERVAS_MONTOS] CHECK ([PRECIO_BASE] >= 0 AND [COMISION_QR] >= 0 AND [DESCUENTO] >= 0 AND [MONTO_TOTAL] >= 0),
        CONSTRAINT [CK_RESERVAS_REEMBOLSO] CHECK ([PORCENTAJE_REEMB] IS NULL OR ([PORCENTAJE_REEMB] BETWEEN 0 AND 100)),
        CONSTRAINT [CK_RESERVAS_CANCELADO_POR] CHECK ([CANCELADO_POR] IS NULL OR [CANCELADO_POR] IN ('CLIENTE','DUENO','ADMIN','SISTEMA'))
    );

    CREATE UNIQUE NONCLUSTERED INDEX [UX_RESERVAS_SLOT_ACTIVO]
    ON [dbo].[RESERVAS]([ID_SLOT])
    WHERE [ESTADO] IN ('PENDIENTE','CONFIRMADA');

    CREATE TABLE [dbo].[OFERTAS](
        [ID_OFERTA]        CHAR(10)       NOT NULL,
        [ID_CANCHA]        CHAR(10)       NOT NULL,
        [ID_DUENO]         CHAR(10)       NOT NULL,
        [ID_SLOT]          CHAR(10)       NULL,
        [PORCENTAJE_DESC]  INT            NOT NULL,
        [PRECIO_OFERTA]    DECIMAL(8,2)   NOT NULL,
        [FECHA_INICIO]     DATETIME2(0)   NOT NULL,
        [FECHA_EXPIRA]     DATETIME2(0)   NOT NULL,
        [ESTADO]           VARCHAR(20)    NOT NULL CONSTRAINT [DF_OFERTAS_ESTADO] DEFAULT ('ACTIVO'),
        [FECHA_CREA]       DATETIME2(0)   NOT NULL CONSTRAINT [DF_OFERTAS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_OFERTAS] PRIMARY KEY CLUSTERED ([ID_OFERTA]),
        CONSTRAINT [FK_OFERTAS_CANCHAS] FOREIGN KEY ([ID_CANCHA]) REFERENCES [dbo].[CANCHAS]([ID_CANCHA]),
        CONSTRAINT [FK_OFERTAS_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [FK_OFERTAS_SLOTS] FOREIGN KEY ([ID_SLOT]) REFERENCES [dbo].[SLOTS]([ID_SLOT]),
        CONSTRAINT [CK_OFERTAS_DESCUENTO] CHECK ([PORCENTAJE_DESC] BETWEEN 1 AND 90),
        CONSTRAINT [CK_OFERTAS_PRECIO] CHECK ([PRECIO_OFERTA] >= 0),
        CONSTRAINT [CK_OFERTAS_FECHAS] CHECK ([FECHA_EXPIRA] > [FECHA_INICIO]),
        CONSTRAINT [CK_OFERTAS_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','INACTIVO','EXPIRADO'))
    );

    CREATE TABLE [dbo].[PAGOS](
        [ID_PAGO]                    CHAR(10)       NOT NULL,
        [ID_RESERVA]                 CHAR(10)       NOT NULL,
        [ID_USER]                    CHAR(10)       NOT NULL,
        [METODO_PAGO]                VARCHAR(20)    NOT NULL,
        [PROVEEDOR]                  VARCHAR(30)    NULL,
        [PROVEEDOR_TRANSACCION_ID]   NVARCHAR(100)  NULL,
        [MONTO]                      DECIMAL(8,2)   NOT NULL,
        [ESTADO]                     VARCHAR(20)    NOT NULL CONSTRAINT [DF_PAGOS_ESTADO] DEFAULT ('PENDIENTE'),
        [RESPUESTA_PROVEEDOR]        VARCHAR(MAX)   NULL,
        [FECHA_PROCESO]              DATETIME2(0)   NOT NULL CONSTRAINT [DF_PAGOS_FECHA_PROCESO] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_PAGOS] PRIMARY KEY CLUSTERED ([ID_PAGO]),
        CONSTRAINT [FK_PAGOS_RESERVAS] FOREIGN KEY ([ID_RESERVA]) REFERENCES [dbo].[RESERVAS]([ID_RESERVA]),
        CONSTRAINT [FK_PAGOS_USUARIOS] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USUARIOS]([ID_USER]),
        CONSTRAINT [CK_PAGOS_METODO] CHECK ([METODO_PAGO] IN ('YAPE','TARJETA','TRANSFERENCIA','EFECTIVO','PLIN','OTRO')),
        CONSTRAINT [CK_PAGOS_ESTADO] CHECK ([ESTADO] IN ('PENDIENTE','PAGADO','FALLIDO','ANULADO','REEMBOLSADO')),
        CONSTRAINT [CK_PAGOS_MONTO] CHECK ([MONTO] >= 0)
    );

    CREATE UNIQUE NONCLUSTERED INDEX [UX_PAGOS_PROVEEDOR_TRANSACCION]
    ON [dbo].[PAGOS]([PROVEEDOR], [PROVEEDOR_TRANSACCION_ID])
    WHERE [PROVEEDOR_TRANSACCION_ID] IS NOT NULL;

    CREATE TABLE [dbo].[COMPROBANTES](
        [ID_COMPROBANTE]  CHAR(10)       NOT NULL,
        [NRO_COMPROBANTE] NVARCHAR(20)   NOT NULL,
        [RUTA_PDF]        NVARCHAR(200)  NOT NULL,
        [FECHA_GENERADA]  DATETIME2(0)   NOT NULL CONSTRAINT [DF_COMPROBANTES_FECHA_GENERADA] DEFAULT (SYSDATETIME()),
        [ID_RESERVA]      CHAR(10)       NOT NULL,
        [ID_USER]         CHAR(10)       NOT NULL,
        CONSTRAINT [PK_COMPROBANTES] PRIMARY KEY CLUSTERED ([ID_COMPROBANTE]),
        CONSTRAINT [UQ_COMPROBANTES_NRO] UNIQUE ([NRO_COMPROBANTE]),
        CONSTRAINT [FK_COMPROBANTES_RESERVAS] FOREIGN KEY ([ID_RESERVA]) REFERENCES [dbo].[RESERVAS]([ID_RESERVA]),
        CONSTRAINT [FK_COMPROBANTES_USUARIOS] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USUARIOS]([ID_USER])
    );

    CREATE TABLE [dbo].[REEMBOLSOS](
        [ID_REEMBOLSO]        CHAR(10)       NOT NULL,
        [ID_PAGO]             CHAR(10)       NOT NULL,
        [PROVEEDOR_REFUND_ID] VARCHAR(50)    NULL,
        [MOTIVO]              VARCHAR(200)   NULL,
        [INTENTOS]            INT            NOT NULL CONSTRAINT [DF_REEMBOLSOS_INTENTOS] DEFAULT (0),
        [ESTADO]              VARCHAR(20)    NOT NULL CONSTRAINT [DF_REEMBOLSOS_ESTADO] DEFAULT ('PENDIENTE'),
        [FECHA_CREA]          DATETIME2(0)   NOT NULL CONSTRAINT [DF_REEMBOLSOS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        [FECHA_PROCESO]       DATETIME2(0)   NULL,
        CONSTRAINT [PK_REEMBOLSOS] PRIMARY KEY CLUSTERED ([ID_REEMBOLSO]),
        CONSTRAINT [FK_REEMBOLSOS_PAGOS] FOREIGN KEY ([ID_PAGO]) REFERENCES [dbo].[PAGOS]([ID_PAGO]),
        CONSTRAINT [CK_REEMBOLSOS_INTENTOS] CHECK ([INTENTOS] >= 0),
        CONSTRAINT [CK_REEMBOLSOS_ESTADO] CHECK ([ESTADO] IN ('PENDIENTE','PROCESADO','RECHAZADO','ERROR'))
    );

    CREATE TABLE [dbo].[REVIEWS](
        [ID_REVIEW]     CHAR(10)       NOT NULL,
        [ID_RESERVA]    CHAR(10)       NOT NULL,
        [ID_USER]       CHAR(10)       NOT NULL,
        [ID_CANCHA]     CHAR(10)       NOT NULL,
        [ID_DUENO]      CHAR(10)       NOT NULL,
        [CALIFICACION]  INT            NOT NULL,
        [COMENTARIOS]   VARCHAR(300)   NULL,
        [FECHA_CREA]    DATETIME2(0)   NOT NULL CONSTRAINT [DF_REVIEWS_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_REVIEWS] PRIMARY KEY CLUSTERED ([ID_REVIEW]),
        CONSTRAINT [FK_REVIEWS_RESERVAS] FOREIGN KEY ([ID_RESERVA]) REFERENCES [dbo].[RESERVAS]([ID_RESERVA]),
        CONSTRAINT [FK_REVIEWS_USUARIOS] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USUARIOS]([ID_USER]),
        CONSTRAINT [FK_REVIEWS_CANCHAS] FOREIGN KEY ([ID_CANCHA]) REFERENCES [dbo].[CANCHAS]([ID_CANCHA]),
        CONSTRAINT [FK_REVIEWS_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [UQ_REVIEWS_RESERVA] UNIQUE ([ID_RESERVA]),
        CONSTRAINT [CK_REVIEWS_CALIFICACION] CHECK ([CALIFICACION] BETWEEN 1 AND 5)
    );

    CREATE TABLE [dbo].[LIQUIDACIONES](
        [ID_LIQUIDACION]  CHAR(10)       NOT NULL,
        [ID_DUENO]        CHAR(10)       NOT NULL,
        [FECHA_INICIO]    DATE           NOT NULL,
        [FECHA_FIN]       DATE           NOT NULL,
        [MONTO_BRUTO]     DECIMAL(8,2)   NOT NULL,
        [COMISION_PGO]    DECIMAL(8,2)   NOT NULL,
        [MONTO_NETO]      DECIMAL(8,2)   NOT NULL,
        [NRO_OPERACION]   VARCHAR(50)    NULL,
        [FECHA_TRANSF]    DATETIME2(0)   NULL,
        [ESTADO]          VARCHAR(20)    NOT NULL CONSTRAINT [DF_LIQUIDACIONES_ESTADO] DEFAULT ('PENDIENTE'),
        CONSTRAINT [PK_LIQUIDACIONES] PRIMARY KEY CLUSTERED ([ID_LIQUIDACION]),
        CONSTRAINT [FK_LIQUIDACIONES_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [CK_LIQUIDACIONES_FECHAS] CHECK ([FECHA_FIN] >= [FECHA_INICIO]),
        CONSTRAINT [CK_LIQUIDACIONES_MONTOS] CHECK ([MONTO_BRUTO] >= 0 AND [COMISION_PGO] >= 0 AND [MONTO_NETO] >= 0),
        CONSTRAINT [CK_LIQUIDACIONES_ESTADO] CHECK ([ESTADO] IN ('PENDIENTE','PAGADA','OBSERVADA','CANCELADA'))
    );

    CREATE TABLE [dbo].[SUSCRIPCIONES](
        [ID_SUSCRIPCION]  CHAR(10)       NOT NULL,
        [ID_DUENO]        CHAR(10)       NOT NULL,
        [PLAN]            VARCHAR(20)    NOT NULL,
        [PRECIO_MENSUAL]  DECIMAL(8,2)   NOT NULL,
        [CANTIDAD_CANCHAS] INT           NOT NULL,
        [FECHA_INICIO]    DATE           NOT NULL,
        [FECHA_FIN]       DATE           NULL,
        [ESTADO]          VARCHAR(20)    NOT NULL CONSTRAINT [DF_SUSCRIPCIONES_ESTADO] DEFAULT ('ACTIVO'),
        CONSTRAINT [PK_SUSCRIPCIONES] PRIMARY KEY CLUSTERED ([ID_SUSCRIPCION]),
        CONSTRAINT [FK_SUSCRIPCIONES_DUENOS] FOREIGN KEY ([ID_DUENO]) REFERENCES [dbo].[DUENOS]([ID_DUENO]),
        CONSTRAINT [CK_SUSCRIPCIONES_PLAN] CHECK ([PLAN] IN ('BASICO','PRO','PREMIUM')),
        CONSTRAINT [CK_SUSCRIPCIONES_PRECIO] CHECK ([PRECIO_MENSUAL] >= 0),
        CONSTRAINT [CK_SUSCRIPCIONES_CANTIDAD] CHECK ([CANTIDAD_CANCHAS] > 0),
        CONSTRAINT [CK_SUSCRIPCIONES_ESTADO] CHECK ([ESTADO] IN ('ACTIVO','VENCIDO','CANCELADO'))
    );

    CREATE TABLE [dbo].[TOKENS_RECUPERACION](
        [ID_TOKEN]      CHAR(10)       NOT NULL,
        [ID_USER]       CHAR(10)       NOT NULL,
        [TOKEN]         NVARCHAR(200)  NOT NULL,
        [FECHA_EXPIRA]  DATETIME2(0)   NOT NULL,
        [ESTADO]        VARCHAR(20)    NOT NULL CONSTRAINT [DF_TOKENS_RECUPERACION_ESTADO] DEFAULT ('PENDIENTE'),
        [FECHA_CREA]    DATETIME2(0)   NOT NULL CONSTRAINT [DF_TOKENS_RECUPERACION_FECHA_CREA] DEFAULT (SYSDATETIME()),
        CONSTRAINT [PK_TOKENS_RECUPERACION] PRIMARY KEY CLUSTERED ([ID_TOKEN]),
        CONSTRAINT [FK_TOKENS_RECUPERACION_USUARIOS] FOREIGN KEY ([ID_USER]) REFERENCES [dbo].[USUARIOS]([ID_USER]),
        CONSTRAINT [UQ_TOKENS_RECUPERACION_TOKEN] UNIQUE ([TOKEN]),
        CONSTRAINT [CK_TOKENS_RECUPERACION_ESTADO] CHECK ([ESTADO] IN ('PENDIENTE','USADO','EXPIRADO','ANULADO'))
    );

    /* ============================================================
       3. DATOS BASE
       ============================================================ */

    INSERT INTO [dbo].[TIPOS_CANCHA]
        ([ID_TIPO_CANCHA], [CODIGO], [NOMBRE], [JUGADORES_POR_EQUIPO], [JUGADORES_TOTAL], [TAMANO], [DESCRIPCION])
    VALUES
        ('TIPO000001', 'F5',  'Futbol 5',  5, 10, 'PEQUENA', 'Cancha pequena para partidos 5 contra 5'),
        ('TIPO000002', 'F6',  'Futbol 6',  6, 12, 'PEQUENA', 'Cancha pequena para partidos 6 contra 6'),
        ('TIPO000003', 'F7',  'Futbol 7',  7, 14, 'MEDIANA', 'Cancha mediana para partidos 7 contra 7'),
        ('TIPO000004', 'F8',  'Futbol 8',  8, 16, 'MEDIANA', 'Cancha mediana para partidos 8 contra 8'),
        ('TIPO000005', 'F11', 'Futbol 11', 11, 22, 'GRANDE',  'Cancha grande reglamentaria para partidos 11 contra 11');

    /* ============================================================
       4. ÍNDICES DE BÚSQUEDA Y RENDIMIENTO
       ============================================================ */

    CREATE NONCLUSTERED INDEX [IX_LOCALES_UBICACION]
    ON [dbo].[LOCALES]([DEPARTAMENTO], [PROVINCIA], [DISTRITO], [ESTADO]);

    CREATE NONCLUSTERED INDEX [IX_LOCALES_DUENO]
    ON [dbo].[LOCALES]([ID_DUENO]);

    CREATE NONCLUSTERED INDEX [IX_CANCHAS_BUSQUEDA]
    ON [dbo].[CANCHAS]([ID_LOCAL], [ID_TIPO_CANCHA], [ESTADO], [PRECIO_BASE]);

    CREATE NONCLUSTERED INDEX [IX_CANCHAS_SUPERFICIE]
    ON [dbo].[CANCHAS]([TIPO_SUPERFICIE], [ES_TECHADA], [TIENE_ILUMINACION]);

    CREATE NONCLUSTERED INDEX [IX_FOTOS_CANCHA]
    ON [dbo].[FOTOS_CANCHA]([ID_CANCHA], [ES_PRINCIPAL], [ORDEN]);

    CREATE NONCLUSTERED INDEX [IX_HORARIOS_CANCHA]
    ON [dbo].[HORARIOS]([ID_CANCHA], [DIA_SEMANA], [ESTADO]);

    CREATE NONCLUSTERED INDEX [IX_SLOTS_BUSQUEDA]
    ON [dbo].[SLOTS]([FECHA], [HORA_INICIO], [ESTADO], [ID_CANCHA])
    INCLUDE ([HORA_FIN], [PRECIO_FINAL]);

    CREATE NONCLUSTERED INDEX [IX_OFERTAS_ACTIVAS]
    ON [dbo].[OFERTAS]([ESTADO], [FECHA_INICIO], [FECHA_EXPIRA], [ID_CANCHA], [ID_SLOT]);

    CREATE NONCLUSTERED INDEX [IX_RESERVAS_USUARIO]
    ON [dbo].[RESERVAS]([ID_USER], [FECHA_CREA] DESC);

    CREATE NONCLUSTERED INDEX [IX_RESERVAS_CANCHA]
    ON [dbo].[RESERVAS]([ID_CANCHA], [ESTADO], [FECHA_CREA] DESC);

    CREATE NONCLUSTERED INDEX [IX_PAGOS_RESERVA]
    ON [dbo].[PAGOS]([ID_RESERVA], [ESTADO]);

    CREATE NONCLUSTERED INDEX [IX_REVIEWS_CANCHA]
    ON [dbo].[REVIEWS]([ID_CANCHA], [FECHA_CREA] DESC)
    INCLUDE ([CALIFICACION]);

    COMMIT TRANSACTION;

    PRINT 'Esquema PichangaGO V2 recreado correctamente.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ERROR_SEVERITY INT = ERROR_SEVERITY();
    DECLARE @ERROR_STATE INT = ERROR_STATE();

    RAISERROR(@ERROR_MESSAGE, @ERROR_SEVERITY, @ERROR_STATE);
END CATCH;
GO
